#!/usr/bin/env python3
"""
script for combining the files containing the gravityspy spectrograms generated by create_gs_fromraw.py
"""

import sys
# sys.path.append('/storage/home/tommaria/thesis/tools')
sys.path.append('../tools')
from tools_gs import *

import h5py
from pathlib import Path
import numpy as np
from os.path import isfile, join
from os import listdir

data_path = Path('/storage/fast/users/tommaria/data/gravityspy/fromraw/training')
files = sorted(listdir(data_path))
print(files)

x = []
y = []
times = []

for file in files:
	if not isfile(join(data_path, file)):
		continue

	with h5py.File(join(data_path, file), 'r') as f:
		x.extend(np.asarray(f['x']))
		y.extend([item.decode('ascii') for item in list(f['y'])])
		times.extend(np.asarray(f['times']))

x = np.asarray(x)
print(x.shape)
print(len(y))
times = np.asarray(times)

y = [item.encode('ascii') for item in y]

data_path = Path('/storage/fast/users/tommaria/data/gravityspy/fromraw')

with h5py.File(join(data_path, 'trainingset_fromraw_centered_2048_Tc_64_gs.hdf5'), 'w') as f:
	f.create_dataset('x', data=x)
	f.create_dataset('y', data=y)
	f.create_dataset('times', data=times)